# arguments for dataset
dataset: CWFID_percent30
nclass: 3
crop_size: 321
data_root: ../semi_sup_data/CWFID/percent_30

# arguments for training
epochs: 80
batch_size: 2
lr: 0.001  # 4GPUs
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
thresh_init: 0.85

# arguments for model
backbone: resnet50
pretrain: True
multi_grid: False
replace_stride_with_dilation: [False, True, True]
#dilations: [6, 12, 18]
dilations: [12, 24, 36]
